# Generated by Django 3.2.12 on 2022-04-07 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('UserFirstName', models.CharField(blank=True, max_length=50)),
                ('UserLastName', models.CharField(blank=True, max_length=50)),
                ('UserEmail', models.CharField(blank=True, max_length=50)),
                ('UserPhoneNumber', models.CharField(blank=True, max_length=10)),
                ('UserBirthDate', models.DateTimeField(blank=True)),
                ('UserProfileImage', models.ImageField(upload_to='UserProfileImages/')),
                ('Datetime', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(blank=True, max_length=50)),
                ('ProductDescription', models.TextField(blank=True)),
                ('ProductType', models.CharField(blank=True, max_length=100)),
                ('ProductImage', models.ImageField(upload_to='ProductImages/')),
                ('ProductFIle', models.FileField(upload_to='ProductFiles/')),
                ('ProductDate', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.usersmodel')),
            ],
        ),
    ]
