# Generated by Django 3.2.12 on 2022-04-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_productsmodel_usersmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='ProductFIle',
            field=models.FileField(blank=True, upload_to='ProductFiles/'),
        ),
    ]
