# Generated by Django 3.2.12 on 2022-04-11 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_productsmodel_productfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadProfuctBulk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductFIle', models.FileField(blank=True, upload_to='BulkProductFiles/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.usersmodel')),
            ],
        ),
    ]
