# Generated by Django 3.2.12 on 2022-04-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_uploadprofuctbulk_uploadproductbulk'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadProductBulks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existingPath', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('eof', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='UploadProductBulk',
        ),
    ]
